server:
  port: 8008
  compression:
    enabled: true
    mime-types: application/json
  tomcat:
    max-connections: 20000
    max-threads: 2000
spring:
  redis:
    host: 172.16.0.124
    port: 6379
    database: 0
